members/urls.py
from django.urls import path
from . import views



app_name = 'members'

urlpatterns = [
    path('', views.index, name='index'),
    path('people/', views.people, name='people'),
]

project/urls.py
from django.contrib import admin
from . import views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('members/', include('members.urls', namespace='members')),
    path('', views.home, name='home'),

]

members/models.py
from django.db import models

# Create your models here.

from django.db import models

class Member(models.Model):
  firstname = models.CharField(max_length=255)
  lastname = models.CharField(max_length=255)
  phone = models.IntegerField()
  joined_date = models.DateField()

members/views.py
# Create your views here.
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')
 
def people(request):
    return render(request,'people.html')

project/views.py
# project/views.py

from django.shortcuts import render

def home(request):
    return render(request, 'index.html')

members/templates/index.html
<!-- members/templates/members/index.html -->
{% extends "members/base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
   
{% block title %} {% endblock %} 
</head>
<link rel="stylesheet" href="{% static 'myfirst.css' %}">
{% block content %}
<body>
    <h1>Welcome to the Home Page</h1>
    <p>This is a simple template for the root URL.</p>
    <a href="{% url 'members:people' %}">Go to people Page</a>
</body>
</html>
{% endblock %}

members/templates/members/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Django asdfgApp{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'myfirst.css' %}">
</head>
<body>
    <header>
        <h1>Welcome to My f App</h1>
    </header>
    <nav>
        <!-- Navigation links go here -->
        <li><a href="{% url 'members:index' %}">Home</a></li>
            <li><a href="{% url 'members:people' %}">About</a></li>
    </nav>
    <main>
        {% block content %}
        <!-- Default content goes here -->
        {% endblock %}
    </main>
    <footer>
        <p>&copy; 2024 My Django App</p>
    </footer>
</body>
</html>

members/templates/people.html
<!-- members/templates/members/index.html -->
{% extends "members/base.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %} {% endblock %} 
    <title>Home Page</title>
</head>
<link rel="stylesheet" href="{% static 'myfirst.css' %}">
{% block content %}
<body>
   <h2> Welcome to the about section </h2>
</body>
</html>
{% endblock %}